name = input("What is your name? ")
age = input("How old are you? ")
city = input("Where do you live? ")
print(f"Welcome {name}!")
print(f"Your age is {age}.")
print(f"You live in {city}.")
#
v1 = float(input("Specify the variable A = "))
v2 = float(input("Specify the variable B = "))
print("A+B=",v1+v2)
print("A-B=",v1-v2)
print("A*B=",v1*v2)
print("A/B=",v1/v2)
#
print("   (⁀⁀⁀⁀⁀⁀⁀⁀⁀⁀⁀⁀⁀⁀⁀⁀)")
print("   (   **       **  )")
print("   (                )")
print("   (   --‿‿‿◊‿‿‿--  )")  
print("   (............... )")
# Або не художник, або не зрозум1в завдання =)
print("   (----------------)")
print("   (   **       **  )")
print("   (                )")
print("   (   ----_!_----  )")  
print("   (............... )")
#